# Generated by Django 4.2.5 on 2023-09-26 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connections', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('75a266e9-c6a6-4c82-ac9a-e9eb0339fcbf'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=700, null=True)),
                ('slug', models.SlugField(default='78d11be1-5698-42e7-9b4d-a2906b8edfba', max_length=100, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('ends_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_ends_at', to='locations.location')),
                ('route', models.ManyToManyField(related_name='scenarios', to='connections.connection')),
                ('starts_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_starts_at', to='locations.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
