# Generated by Django 4.2.5 on 2023-09-26 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0006_alter_location_label'),
        ('connections', '0004_alter_connection_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(default='126db1b7-d99a-4f0c-a654-6400f5972b85', max_length=100, unique=True)),
                ('connections', models.ManyToManyField(related_name='map_routes', to='connections.connection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('ends_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_ends_at', to='locations.location')),
                ('locations', models.ManyToManyField(related_name='map_routes', to='locations.location')),
                ('starts_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_starts_at', to='locations.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
