# Generated by Django 4.2.5 on 2023-09-27 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0005_alter_connection_created_by'),
        ('locations', '0008_alter_location_created_by_alter_location_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map_routes', '0002_alter_maproute_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maproute',
            name='ends_at',
        ),
        migrations.AlterField(
            model_name='maproute',
            name='connections',
            field=models.ManyToManyField(related_name='map_route', to='connections.connection'),
        ),
        migrations.AlterField(
            model_name='maproute',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maproute',
            name='locations',
            field=models.ManyToManyField(related_name='map_route', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='maproute',
            name='name',
            field=models.CharField(default='c3ee2196-9b45-4b7e-a1f2-91d8fedb9efa', max_length=120),
        ),
        migrations.AlterField(
            model_name='maproute',
            name='slug',
            field=models.SlugField(default='b7334176-e439-443a-868b-21eb75c51a27', max_length=100, unique=True),
        ),
    ]
