# Generated by Django 4.2.5 on 2023-09-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_routes', '0003_remove_maproute_ends_at_alter_maproute_connections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maproute',
            name='connections',
        ),
        migrations.RemoveField(
            model_name='maproute',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='maproute',
            name='starts_at',
        ),
        migrations.AlterField(
            model_name='maproute',
            name='name',
            field=models.CharField(default='dbbe7303-6820-4836-b621-164328a64c4c', max_length=120),
        ),
        migrations.AlterField(
            model_name='maproute',
            name='slug',
            field=models.SlugField(default='635e3520-db85-4306-8506-8bf4332c5af8', max_length=100, unique=True),
        ),
    ]
