# Generated by Django 4.2.5 on 2023-09-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_routes', '0004_remove_maproute_connections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maproute',
            name='name',
            field=models.CharField(default='12694e7f-acda-41a3-97c5-b3fe1e279643', max_length=120),
        ),
        migrations.AlterField(
            model_name='maproute',
            name='slug',
            field=models.SlugField(default='55979f88-9ebe-44ad-9015-accaeda03e60', max_length=100, unique=True),
        ),
    ]
