# Generated by Django 4.2.5 on 2023-09-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_routes', '0005_alter_maproute_name_alter_maproute_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maproute',
            name='name',
            field=models.CharField(default='af2bc113-d90b-4458-af1c-06cf1113e61e', max_length=120),
        ),
        migrations.AlterField(
            model_name='maproute',
            name='slug',
            field=models.SlugField(default='1acd8e24-2f58-49bc-88e7-9d9019536ae0', max_length=100, unique=True),
        ),
    ]
