# Generated by Django 4.2.5 on 2023-09-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_routes', '0006_alter_maproute_name_alter_maproute_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maproute',
            name='name',
            field=models.CharField(default='1cf343c1-6599-4f10-90dc-15f571bc130c', max_length=120),
        ),
        migrations.AlterField(
            model_name='maproute',
            name='slug',
            field=models.SlugField(default='3159e921-0581-47a4-9ca6-6a70e3e5ef78', max_length=100, unique=True),
        ),
    ]
