# Generated by Django 4.2.5 on 2023-09-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_routes', '0007_alter_maproute_name_alter_maproute_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maproute',
            name='name',
            field=models.CharField(default='22606dd4-8d2c-45b5-b80f-41aabb11dbe7', max_length=120),
        ),
        migrations.AlterField(
            model_name='maproute',
            name='slug',
            field=models.SlugField(default='51371d81-5e60-4741-9509-89363d2fe4d3', max_length=100, unique=True),
        ),
    ]
