# Generated by Django 4.2.5 on 2023-09-27 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('map_routes', '0008_alter_maproute_name_alter_maproute_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maproute',
            name='name',
            field=models.CharField(default=uuid.uuid4, max_length=120),
        ),
        migrations.AlterField(
            model_name='maproute',
            name='slug',
            field=models.SlugField(default='62f90e45-0b55-44ad-8f90-9661a8ebeab4', max_length=100, unique=True),
        ),
    ]
