# Generated by Django 4.2.5 on 2023-09-27 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('map_routes', '0009_alter_maproute_name_alter_maproute_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maproute',
            name='name',
            field=models.CharField(default=uuid.uuid4, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='maproute',
            name='slug',
            field=models.SlugField(default='85b65a27-8ef4-4f2c-b7c3-76904c085519', max_length=100, unique=True),
        ),
    ]
