# Generated by Django 4.2.5 on 2023-09-26 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('75a266e9-c6a6-4c82-ac9a-e9eb0339fcbf'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.IntegerField(default=0)),
                ('bidirectional', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('first_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_first_location', to='locations.location')),
                ('second_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_second_location', to='locations.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
