# Generated by Django 4.2.5 on 2023-09-27 13:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('map_routes', '0007_alter_maproute_name_alter_maproute_slug'),
        ('connections', '0006_connection_map_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='map_route',
            field=models.ForeignKey(default=uuid.UUID('3e4d65d1-b103-420b-97d7-6d8b0068d8ef'), on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='map_routes.maproute'),
        ),
    ]
