# Generated by Django 4.2.5 on 2023-09-27 14:11

from django.db import migrations, models
import django.db.models.deletion
import map_routes.models


class Migration(migrations.Migration):

    dependencies = [
        ('map_routes', '0008_alter_maproute_name_alter_maproute_slug'),
        ('connections', '0007_alter_connection_map_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='map_route',
            field=models.ForeignKey(default=map_routes.models.MapRoute.get_default_pk, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='map_routes.maproute'),
        ),
    ]
