# Generated by Django 4.2.5 on 2023-09-26 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('75a266e9-c6a6-4c82-ac9a-e9eb0339fcbf'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(default='9d2a7c318f334e23a88d', max_length=20, unique=True)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('position_x', 'position_y')},
            },
        ),
    ]
