# Generated by Django 4.2.5 on 2023-09-26 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='label',
            field=models.CharField(default='d9f48dbb29724f35b823', max_length=20, unique=True),
        ),
    ]
