# Generated by Django 4.2.5 on 2023-09-26 21:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_location_id_alter_location_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='label',
            field=models.CharField(default='6163ea24d9de4f618da9', max_length=20, unique=True),
        ),
    ]
