# Generated by Django 4.2.5 on 2023-09-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_location_id_alter_location_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='label',
            field=models.CharField(default='e128abd25c53485093b7', max_length=20, unique=True),
        ),
    ]
