# Generated by Django 4.2.5 on 2023-09-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_alter_location_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='label',
            field=models.CharField(default='c5d6f23b6b4c45f39538', max_length=20, unique=True),
        ),
    ]
