# Generated by Django 4.2.5 on 2023-09-27 13:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('map_routes', '0006_alter_maproute_name_alter_maproute_slug'),
        ('locations', '0008_alter_location_created_by_alter_location_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='map_route',
            field=models.ForeignKey(default=uuid.UUID('4bb94c41-6065-43d5-9d74-e7c0237a59cc'), on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='map_routes.maproute'),
        ),
        migrations.AlterField(
            model_name='location',
            name='label',
            field=models.CharField(default='0bd825d5468f45ff8313', max_length=20),
        ),
    ]
