# Generated by Django 4.2.5 on 2023-09-27 13:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('map_routes', '0007_alter_maproute_name_alter_maproute_slug'),
        ('locations', '0009_location_map_route_alter_location_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='label',
            field=models.CharField(default='001cc02253bf473687f0', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='map_route',
            field=models.ForeignKey(default=uuid.UUID('3e4d65d1-b103-420b-97d7-6d8b0068d8ef'), on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='map_routes.maproute'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('label', 'map_route'), name='unique_label_per_map_route'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('position_x', 'position_y', 'map_route'), name='unique_positions_per_map_route'),
        ),
    ]
