# Generated by Django 4.2.5 on 2023-09-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_alter_location_label_alter_location_map_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='label',
            field=models.CharField(default='23760697c5e0404b8a50', max_length=20),
        ),
    ]
