# Generated by Django 4.2.5 on 2023-09-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_alter_location_label'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='location',
            name='label',
            field=models.CharField(default='fd7dd5c2affd4d6fb74f', max_length=20),
        ),
    ]
