# Generated by Django 4.2.5 on 2023-09-26 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='slug',
            field=models.SlugField(default='efd7791b-27c1-4ad1-bedc-5edc75ae83fb', max_length=100, unique=True),
        ),
    ]
