# Generated by Django 4.2.5 on 2023-09-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_alter_connection_id'),
        ('scenarios', '0002_alter_scenario_id_alter_scenario_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='route',
            field=models.ManyToManyField(null=True, related_name='scenarios', to='connections.connection'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='slug',
            field=models.SlugField(default='bedac9d9-3648-4016-b374-83a06f93e702', max_length=100, unique=True),
        ),
    ]
