# Generated by Django 4.2.5 on 2023-09-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_alter_connection_id'),
        ('locations', '0003_alter_location_label'),
        ('scenarios', '0003_alter_scenario_route_alter_scenario_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='route',
        ),
        migrations.AddField(
            model_name='scenario',
            name='connections',
            field=models.ManyToManyField(null=True, related_name='scenario', to='connections.connection'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='locations',
            field=models.ManyToManyField(related_name='scenario', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='slug',
            field=models.SlugField(default='32ff7d42-5223-40d8-8850-0fdda7bee7d9', max_length=100, unique=True),
        ),
    ]
